trainer:
  name: Trainer
  num_epochs: 400
  output_dir: experiments/fire

model:
  name: efficientnet_b3
  num_classes: 1 

dataset:
  name: DataLoader
  root: /home/cchoi/fire/efficientnet-pytorch/efficientnet/datasets/fire_data
  batch_size: 32
  image_size: 224
 # num_workers: 28

optimizer:
  name: SGD
  lr: 1.25e-2
  weight_decay: 1.e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: MultiStepLR
  milestones: [100, 200, 300]
  gamma: 0.1
